name: personal_expenses
description: App designed to help people to have a better control over their spendings.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  brasil_fields: ^1.1.3
  cupertino_icons: ^1.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  path_provider: ^2.0.2
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png"
  adaptative_icon_background: "#4B1AC3"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Fira-Sans
      fonts:
        - asset: assets/fonts/Fira_Sans/FiraSans-Black.ttf
          weight: 900
        - asset: assets/fonts/Fira_Sans/FiraSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Fira_Sans/FiraSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Fira_Sans/FiraSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Fira_Sans/FiraSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Fira_Sans/FiraSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Fira_Sans/FiraSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Fira_Sans/FiraSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Fira_Sans/FiraSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fira_Sans/FiraSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Fira_Sans/FiraSans-Regular.ttf
        - asset: assets/fonts/Fira_Sans/FiraSans-Italic.ttf
          style: italic
        - asset: assets/fonts/Fira_Sans/FiraSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Fira_Sans/FiraSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Fira_Sans/FiraSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Fira_Sans/FiraSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Fira_Sans/FiraSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/Fira_Sans/FiraSans-ThinItalic.ttf
          weight: 100
          style: italic
